name: "Update Versions List from repology.org"

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync-files:
    name: "Run sync"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Run lister"
        run: |
          chmod a+x repology-updater.sh
          ./repology-updater.sh

      - name: "Push to Source"
        run: |
          git config --global user.name "ivan-hc"
          git config --global user.email "noreply@github.com"
          git add versions-list
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "Sync files from source repository"
            git push && echo "Sync to Source succeeded" >> $GITHUB_STEP_SUMMARY
          fi
